### ISSUE TITLE
Your code has an issue with the line

### ISSUE THREAD

**Issue by naveen-98** [juliandivakaran/cryptopy#1]
It seems like you are trying to use a client object to call a get_historical_klines method, but the client class does not seem to have this method. You need to make sure that the client class or module you are importing has a method named get_historical_klines that can retrieve historical Klines.

If you have the get_historical_klines method defined in the client class, make sure it's properly imported and instantiated. If it's part of some external library or module, make sure you have the correct import statement for that library or module.

Assuming the get_historical_klines method is part of the client class, and you have instantiated the client object correctly, your code should work as expected. Please check the client module and ensure that it has the required method. If there is still an issue, you might need to provide more details about the client module or class you are using.

**Comment by juliandivakaran** [comment]
get_historical_klines getting from the client model inside
